export default {
  openLoadingModal: 'openLoadingModal',
  closeLoadingModal: 'closeLoadingModal',
  openAccountsMenu: 'openAccountsMenu',
  openNetworksMenu: 'openNetworksMenu',
  openConnectInpageDApp: 'openConnectInpageDApp',
  openInpageDAppSign: 'openInpageDAppSign',
  openInpageDAppSendTransaction: 'openInpageDAppSendTransaction',
  openAddEthereumChain: 'openAddEthereumChain',
  openAddAsset: 'openAddAsset',
  openRequestFundsModal: 'openRequestFundsModal',
  openSendFundsModal: 'openSendFundsModal',
  openInappBrowser: 'openInappBrowser',
  openMyAddressQRCode: 'openMyAddressQRCode',
  openGlobalQRScanner: 'openGlobalQRScanner',
  drawerSwipeEnabled: 'drawer-swipeEnabled',
  wc_request: 'wc_request',
  walletconnect2_pair_request: 'walletconnect2_pair_request',

  CodeScan_wallet3sync: 'CodeScan-wallet3sync:',
  CodeScan_64Length: 'CodeScan-64Length',
  openBackupSecretTip: 'openBackupSecretTip',
  userSecretsNotVerified: 'userSecretsNotVerified',
  openUrl: 'openUrl',
  openUrlInPageId: (pageId: number) => `openUrl_page${pageId}`,
  openBrowser: 'openBrowser',
  codeScan: {
    ethereum: 'CodeScan-ethereum',
    address: 'CodeScan-0x',
    walletconnect: 'CodeScan-wc:',
  },
};
