export default {
  openLoadingModal: 'openLoadingModal',
  closeLoadingModal: 'closeLoadingModal',
  openAccountsMenu: 'openAccountsMenu',
  openNetworksMenu: 'openNetworksMenu',
  openConnectInpageDApp: 'openConnectInpageDApp',
  openInpageDAppSign: 'openInpageDAppSign',
  openInpageDAppSendTransaction: 'openInpageDAppSendTransaction',
  openAddEthereumChain: 'openAddEthereumChain',
  openAddAsset: 'openAddAsset',
  openRequestFundsModal: 'openRequestFundsModal',
  openSendFundsModal: 'openSendFundsModal',
  openInappBrowser: 'openInappBrowser',
  drawerSwipeEnabled: 'drawer-swipeEnabled',
  wc_request: 'wc_request',
  CodeScan_wc: 'CodeScan-wc:',
  CodeScan_https: 'CodeScan-https:',
  CodeScan_wallet3sync: 'CodeScan-wallet3sync:',
};
