export default {
  openLoadingModal: 'openLoadingModal',
  closeLoadingModal: 'closeLoadingModal',
  openAccountsMenu: 'openAccountsMenu',
  openNetworksMenu: 'openNetworksMenu',
  openConnectInpageDApp: 'openConnectInpageDApp',
  openInpageDAppSign: 'openInpageDAppSign',
  openInpageDAppSendTransaction: 'openInpageDAppSendTransaction',
  openAddEthereumChain: 'openAddEthereumChain',
  openAddAsset: 'openAddAsset',
  openRequestFundsModal: 'openRequestFundsModal',
  openSendFundsModal: 'openSendFundsModal',
  openInappBrowser: 'openInappBrowser',
  openMyAddressQRCode: 'openMyAddressQRCode',
  openGlobalQRScanner: 'openGlobalQRScanner',
  openShardsDistribution: 'openShardsDistribution',
  openShardReceiver: 'openShardReceiver',
  openShardRedistributionReceiver: 'openShardRedistributionReceiver',
  openShardsAggregator: 'openShardsAggregator',
  openShardProvider: 'openShardProvider',
  openKeyRecoveryRequestor: 'openKeyRecoveryRequestor',
  openKeyRecoveryProvider: 'openKeyRecoveryProvider',
  openGlobalPasspad: 'openGlobalPasspad',
  drawerSwipeEnabled: 'drawer-swipeEnabled',

  wc_request: 'wc_request',

  walletconnect: {
    notSupportedSessionProposal: 'walletconnect2_not_supported_session_proposal',
    pairing_request: 'walletconnect2_pairing_request',
  },

  CodeScan_wallet3sync: 'CodeScan-wallet3sync:',
  CodeScan_64Length: 'CodeScan-64Length',
  openUpgradeWalletTip: 'openUpgradeWalletTip',

  openUrl: 'openUrl',
  openUrlInPageId: (pageId: number) => `openUrl_page${pageId}`,
  openBrowser: 'openBrowser',
  codeScan: {
    ethereum: 'CodeScan-ethereum',
    address: 'CodeScan-0x',
    walletconnect: 'CodeScan-wc:',
  },
};
